### ISSUE TITLE
Update First Derivative Test Statement

### ISSUE THREAD

**Issue by tomgonzalez** [DaltonStateCollege/calculus-text#41]
update the first derivative test statement per Sandi's suggestions.

**Comment by mjjoseph** [comment]
I changed the "f is differentiable on I" condition to be "continuous on I" and "differentiable on I except possibly at c" because a function like |x| has a relative min where it's not differentiable.  I believe that was his suggestion (he mentioned it to me).  Unless he had others, so I'll leave this open.  I also fixed "extrema" to the singular "extremum".  I added several 1st deriv test problems involving transcendental functions to the exercises (those were seriously lacking).
